#!/bin/sh
#
echo "determining branch"
branch=$(echo "$1" | cut -d/ -f3);
worktree=""
runsync=false
if [ "master" = "$branch" ]
then
   worktree="/var/www/vhosts/masterdomain.com"
   runsync=true
fi
if [ "develop" = "$branch" ]
then
    worktree="/var/www/vhosts/testdomain.com"
fi

# do stuff if worktree is not empty
if [ ! -z "$worktree" ]
then
    echo "branch $branch deployed to $worktree"
    # update head and index - to avoid changed timstamp after checkout
    git symbolic-ref HEAD refs/heads/$branch
    git --work-tree="$worktree" update-index --refresh
    # checkout files to worktree
    git --work-tree="$worktree" checkout $branch -f
    if [ $runsync = true ]; then
        #run sync scripts
        :
    fi
fi
